### ISSUE TITLE
Extension freezes computer when pressing enter, even if the service is off

### ISSUE THREAD

**Issue by safazi** [AIIX/Mycroft-AI-Gnome-Shell-Extension#5]
I am running 64 bit Fedora 25. Pressing enter in the Enter Query box will immediately freeze the computer. This happens even if the service is off. There were no errors in installation.

**Comment by AIIX** [comment]
Are you using the latest version of mycroft and the extension ? please attach a debug log:  journalctl /usr/bin/gnome-shell -f -o cat

**Comment by AIIX** [comment]
There seems to be some issue with key-press-events on keyboard input. I haven't yet figured it out and it seems to be currently only affecting Fedora 25 as on Ubuntu 16.10 it seems to be working fine. I am attaching a workaround extension to this message which has a send button below the enter query box instead of pressing enter(which is disabled in this). Until i can find a fix this is the best option. 
[Mycroft-AI-Gnome-Shell-Extension-fedora.zip](https://github.com/AIIX/Mycroft-AI-Gnome-Shell-Extension/files/695162/Mycroft-AI-Gnome-Shell-Extension-fedora.zip)

To Install this you can just replace the extension.js file from the zip in this folder: /home/$USER/.local/share/gnome-shell/extensions/mycroftaignome@aix.com/ and restart the session.

**Comment by Abhinav1217** [comment]
Fedora 25 defaults to wayland instead of x.org, Maybe that is can be the root of issue. Synapsis is also not working. Spotify also crashes for the same reason in the begining before they pushed a fix. 

Another cause of crash can be because wayland has removed apis related to legacy tray. [Topicon extension also have issues in F25 because of it](https://mail.gnome.org/archives/gnome-shell-list/2016-September/msg00005.html).  Basically any app which uses status tray api will crash. That is the reason synapsis is not working.

I have for time being switched to xorg during login to work things normally.

**Comment by safazi** [comment]
switching to xorg fixed the problem.

**Comment by Abhinav1217** [comment]
Switching to xorg is a temporary fix for fedora. Both fedora and gnome-shell will move towards wayland permanently.

**Comment by AIIX** [comment]
I will look into a fix for Wayland and will work something out by the next release as currently I am tied up with getting websockets to directly work from the extension itself getting rid of external dependencies of python and dbus.  Additionally supporting the current version separately for Wayland doesn't make much sense at the moment as most are still on xorg

**Comment by AIIX** [comment]
Keeping this issue open until its fixed for Wayland

**Comment by Abhinav1217** [comment]
Thanks for keeping it open.  For wayland, if the problem is only because of status icon api, you can have a switch to disable it for wayland. Read this on discussion of synapsis app. There is a discussion to not use quick access for synapsis on wayland untill some alternative is provided by gnome itself.  I am sure they have to provide some way quick because lots of major apps have status icon as their only interface. https://wiki.gnome.org/Design/Whiteboards/StatusIcons

**Comment by IceWreck** [comment]
I am on Arch Gnome on Xorg and I too have this freeze. This is not a Wayland issue.

**Comment by AIIX** [comment]
IceWreck, the development of this extension has been depreciated here, the new extension work is happening else where, will notify on release(Soon(In the coming days)) 😄. All previous issues should stand resolved in the new release.

**Comment by Abhinav1217** [comment]
Looking forward to try out the new extension. Even though I have stopped using Mycroft AI.  I would love to test it out.

**Comment by AIIX** [comment]
New Extension Video: https://youtu.be/NvG0sUHpBJQ
Download Link: https://extensions.gnome.org/extension/1197/mycroft-assistant/
Development of the extension is moved to: https://github.com/lolstring/gnome-shell-extension-mycroft

**Comment by kangfredy** [comment]
hi i have issue when enable mycroft from gnome..it make freeze screen.but mycroft has been active..i can speak with mycroft but my screen still freeze
